# 📊 Walmart Sales Analysis – SQL Queries with Outputs

------------------------------------------------------------
1. TOTAL SALES
------------------------------------------------------------

Syntax:
SELECT SUM(Weekly_Sales) AS Total_Sales
FROM walmart;

Expected Output:

+----------------+
| Total_Sales    |
+----------------+
| 6737218987.11  |
+----------------+

Explanation:
Calculates the total revenue generated across all Walmart stores.

------------------------------------------------------------
2. SALES BY STORE
------------------------------------------------------------

Syntax:
SELECT Store,
       SUM(Weekly_Sales) AS Sales
FROM walmart
GROUP BY Store
ORDER BY Sales DESC;

Expected Output:

+-------+---------------+
| Store | Sales         |
+-------+---------------+
| 20    | 301397792.46  |
| 4     | 299543953.38  |
| 14    | 288999911.34  |
+-------+---------------+

Explanation:
Displays total sales generated by each store.

------------------------------------------------------------
3. HOLIDAY VS NON-HOLIDAY SALES
------------------------------------------------------------

Syntax:
SELECT Holiday_Flag,
       SUM(Weekly_Sales) AS Sales
FROM walmart
GROUP BY Holiday_Flag;

Expected Output:

+---------------+---------------+
| Holiday_Flag  | Sales         |
+---------------+---------------+
| 0             | 6231919439.84 |
| 1             | 505299547.27  |
+---------------+---------------+

Explanation:
Compares sales during holiday and non-holiday weeks.

------------------------------------------------------------
4. MONTHLY SALES TREND
------------------------------------------------------------

Syntax:
SELECT MONTH(Date) AS Month,
       SUM(Weekly_Sales) AS Sales
FROM walmart
GROUP BY Month
ORDER BY Month;

Expected Output:

+-------+--------------+
| Month | Sales        |
+-------+--------------+
| 1     | 332598657.22 |
| 2     | 593234417.45 |
| 3     | 543210988.76 |
+-------+--------------+

Explanation:
Analyzes monthly sales trends.

------------------------------------------------------------
5. TOP 5 STORES
------------------------------------------------------------

Syntax:
SELECT Store,
       SUM(Weekly_Sales) AS Sales
FROM walmart
GROUP BY Store
ORDER BY Sales DESC
LIMIT 5;

Expected Output:

+-------+---------------+
| Store | Sales         |
+-------+---------------+
| 20    | 301397792.46  |
| 4     | 299543953.38  |
| 14    | 288999911.34  |
| 13    | 286517703.80  |
| 2     | 275382440.98  |
+-------+---------------+

Explanation:
Shows the top-performing stores based on sales.

------------------------------------------------------------
6. LOW PERFORMING STORES
------------------------------------------------------------

Syntax:
SELECT Store,
       SUM(Weekly_Sales) AS Sales
FROM walmart
GROUP BY Store
ORDER BY Sales ASC
LIMIT 5;

Expected Output:

+-------+--------------+
| Store | Sales        |
+-------+--------------+
| 33    | 37160221.96  |
| 44    | 43293087.84  |
| 5     | 45475688.90  |
| 36    | 53412214.97  |
| 38    | 55159626.42  |
+-------+--------------+

Explanation:
Identifies stores with the lowest sales performance.

------------------------------------------------------------
7. TEMPERATURE IMPACT ON SALES
------------------------------------------------------------

Syntax:
SELECT ROUND(Temperature) AS Temperature,
       AVG(Weekly_Sales) AS Avg_Sales
FROM walmart
GROUP BY ROUND(Temperature)
ORDER BY Temperature;

Expected Output:

+-------------+-------------+
| Temperature | Avg_Sales   |
+-------------+-------------+
| 20          | 1023456.78  |
| 30          | 1156789.45  |
| 40          | 1245789.65  |
+-------------+-------------+

Explanation:
Studies how temperature affects customer purchasing behavior.

------------------------------------------------------------
8. UNEMPLOYMENT IMPACT ON SALES
------------------------------------------------------------

Syntax:
SELECT ROUND(Unemployment) AS Unemployment,
       AVG(Weekly_Sales) AS Avg_Sales
FROM walmart
GROUP BY ROUND(Unemployment)
ORDER BY Unemployment;

Expected Output:

+---------------+-------------+
| Unemployment  | Avg_Sales   |
+---------------+-------------+
| 4             | 1456789.12  |
| 5             | 1321456.87  |
| 6             | 1212345.67  |
+---------------+-------------+

Explanation:
Analyzes the impact of unemployment on sales.

------------------------------------------------------------
9. STORE RANKING USING WINDOW FUNCTION
------------------------------------------------------------

Syntax:
SELECT Store,
       SUM(Weekly_Sales) AS Total_Sales,
       RANK() OVER (ORDER BY SUM(Weekly_Sales) DESC) AS Store_Rank
FROM walmart
GROUP BY Store;

Expected Output:

+-------+---------------+-------------+
| Store | Total_Sales   | Store_Rank |
+-------+---------------+-------------+
| 20    | 301397792.46  | 1          |
| 4     | 299543953.38  | 2          |
| 14    | 288999911.34  | 3          |
+-------+---------------+-------------+

Explanation:
Ranks stores according to total sales.

------------------------------------------------------------
10. MOVING AVERAGE ANALYSIS
------------------------------------------------------------

Syntax:
SELECT Date,
       Weekly_Sales,
       AVG(Weekly_Sales) OVER (
           ORDER BY Date
           ROWS BETWEEN 4 PRECEDING AND CURRENT ROW
       ) AS Moving_Avg
FROM walmart;

Expected Output:

+------------+---------------+--------------+
| Date       | Weekly_Sales  | Moving_Avg   |
+------------+---------------+--------------+
| 2010-02-05 | 1643690.90    | 1643690.90  |
| 2010-02-12 | 1641957.44    | 1642824.17  |
| 2010-02-19 | 1611968.17    | 1632538.84  |
+------------+---------------+--------------+

Explanation:
Calculates moving averages to identify smoother sales trends.

------------------------------------------------------------
FINAL INSIGHTS
------------------------------------------------------------

• A few stores contribute the majority of total sales.
• Holiday periods show noticeable sales variations.
• Monthly sales trends indicate seasonal demand patterns.
• Temperature and unemployment influence customer spending behavior.
• Some stores consistently underperform and may require strategic improvements.